name: DEPLOY

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Parse DEPLOY secrets into environment variables
    - name: Parse DEPLOY secret
      id: parse_deploy
      run: |
        echo "${{ secrets.DEPLOY }}" | while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done

    # Step 3: Upload files to the FTP server
    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ env.FTP_SERVER }}          # FTP server address
        username: ${{ env.FTP_USERNAME }}      # FTP username
        password: ${{ env.FTP_PASSWORD }}      # FTP password
        local-dir: ./                          # Adjust to the directory to deploy
        server-dir: /securedswiftpay.com/                 # Target directory on the FTP server
        log-level: verbose                     # Enable verbose logs for debugging
        create-only: true                      # Allow creation of missing directories
